version: '3.3'
services:
  node:
    container_name: node
    image: 'node:latest'
    working_dir: /home/node/app
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - api_indy
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - api_indy
networks:
  api_indy:
    driver: bridge